# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $ Header:$
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

DESCRIPTION="Disk free based on Filesys::Statvfs"
HOMEPAGE="http://search.cpan.org/search?query=Filesys-Df&mode=dist"
SRC_URI="mirror://cpan/authors/id/I/IG/IGUTHRIE/${P}.tar.gz"

IUSE=""
SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~x86"

