.TH elogviewer 1 "October 07, 2006" "elogviewer -- An interface to Portage's ELOG system"

.SH NAME
elogviewer \-\- a program to easily manage elog files created by Portage during emerge

.SH DESCRIPTION
This manual page explains the
.B elogviewer
program. This program lists all elogs created during emerges of
packages from Portage, the package manager of Gentoo Linux.  So all
warnings or informational messages generated during an update can be
reviewed at one glance.

.SH USAGE

To generate elogs, the user needs to tell Portage to activate the
saving features for the ELOG facilities in his /etc/make.conf file via
the line

.RS 4
PORTAGE_ELOG_SYSTEM="save"
.RE

and choose at least one out of

.RS 4
PORTAGE_ELOG_CLASSES="warn info error log"
.RE

Further prerequisite ist the elog directory (in most cases
/var/log/portage/elog/, see variable $PORT_LOGDIR), which may need to
be created and belong to the portage group. If the user wants to start
the program as non-root, he needs to add himself to portage group.
For more information on the ELOG system, see /etc/make.conf.example.

The program allows to select the ebuild functions in which to look for
messages, so unpack messages about patching can be disabled while
still having warnings from the post installation function without
informational messaes.  elogs can be deleted individually or all in
one step.

.SH BUGS
For bugs in this man page contact <gentoo@faulhammer.org> and for problems with the program the original author Mathias Laurin <synss@cashette.com>.

There are a few the author will address when time permits.  But elogviewer does what it was created for.
.PP
Prints an error message after the last elog has been deleted.
.PP
Error messages should be routed to the error dev on not the console. 
.PP
No del-key shortcut.
.PP
The filter is getting inconvenient.

.SH ENVIRONMENT

Uses 
.B PORT_LOGDIR
from 
.B /etc/make.conf (5)
. Passing 
.B PORT_LOGDIR
on the command line overwrites the defaults.

.SH SEE ALSO
/etc/make.conf.example

.SH AUTHOR
Mathias Laurin <synss@cashette.com> for the program, Christian
Faulhammer <gentoo@faulhammer.org> for this man page