#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need localmount
	after bootmisc modules isapnp coldplug hotplug
	before net
}

start() {
	ebegin "Starting timer_entropyd"
	start-stop-daemon --start --quiet \
		--exec /usr/sbin/timer_entropyd > /dev/null
	eend $?
}

stop() {
	ebegin "Stopping timer_entropyd"
	start-stop-daemon --stop --quiet --exec /usr/sbin/timer_entropyd
	eend $?
}
