--- Makefile.in.old	2009-04-06 15:43:15.000000000 +0200
+++ Makefile.in	2011-12-27 04:08:01.000000000 +0100
@@ -1,8 +1,6 @@
 
-CCFLAGS = -fPIC -pipe -Wall -g 
-CFLAGS = $(GTK_CFLAGS) $(SOUP_CFLAGS) -I.
-CC = gcc $(ARCHOPTS) -g
-CCSLOW = gcc -O0 -g
+CFLAGS+=-fPIC $(GTK_CFLAGS) $(SOUP_CFLAGS) -I.
+CC?=gcc
 
 # ----------------------------------------------------------------------------
 
@@ -14,35 +12,35 @@
 MODULES = computer.so devices.so benchmark.so network.so
 
 all:	$(OBJECTS) $(MODULES)
-	$(CC) $(CCFLAGS) -o hardinfo -Wl,-export-dynamic $(OBJECTS) $(GTK_LIBS) \
+	$(CC) $(CFLAGS) -o hardinfo -Wl,-export-dynamic $(OBJECTS) $(GTK_LIBS) \
 		$(SOUP_LIBS)
 
 md5.o:
-	$(CCSLOW) $(CCFLAGS) $(CFLAGS) -c md5.c -o $@
+	$(CC) $(CFLAGS) -c md5.c -o $@
 
 blowfish.o:
-	$(CCSLOW) $(CCFLAGS) $(CFLAGS) -c blowfish.c -o $@
+	$(CC) $(CFLAGS) -c blowfish.c -o $@
 
 sha1.o:
-	$(CCSLOW) $(CCFLAGS) $(CFLAGS) -c sha1.c -o $@
+	$(CC) $(CFLAGS) -c sha1.c -o $@
 
 fbench.o:
-	$(CCSLOW) $(CCFLAGS) $(CFLAGS) -c fbench.c -o $@
+	$(CC) $(CFLAGS) -c fbench.c -o $@
 
 fftbench.o:
-	$(CCSLOW) $(CCFLAGS) $(CFLAGS) -c fftbench.c -o $@
+	$(CC) $(CFLAGS) -c fftbench.c -o $@
 
 nqueens.o:
-	$(CCSLOW) $(CCFLAGS) $(CFLAGS) -c nqueens.c -o $@
+	$(CC) $(CFLAGS) -c nqueens.c -o $@
 
 benchmark.so:	benchmark.c
 	make $(BENCHMARK_OBJECTS)
-	$(CCSLOW) $(CCFLAGS) $(CFLAGS) -o $@ -shared $< $(BENCHMARK_OBJECTS) \
+	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ -shared $< $(BENCHMARK_OBJECTS) \
 		$(GTK_FLAGS) $(GTK_LIBS)
 	ln -sf ../$@ modules
 
 %.so:	%.c
-	$(CC) $(CCFLAGS) $(CFLAGS) -o $@ -shared $< $(GTK_FLAGS) $(GTK_LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ -shared $< $(GTK_FLAGS) $(GTK_LIBS)
 	ln -sf ../$@ modules
 	
 clean:
