--- Makefile	2008-03-03 13:59:06.000000000 +0100
+++ Makefile.new	2008-03-03 17:39:07.000000000 +0100
@@ -1,13 +1,13 @@
-CC = gcc
 INC = $(JAVA_HOME)/include
-CFLAGS = -Wall -O3 -fPIC
-LDFLAGS = -shared -Wl,-soname,libnative.so -I$(INC) -I$(INC)/linux
+CFLAGS += -Wall
+LDFLAGS += -shared -Wl,-soname,libnative.so -I$(INC) -I$(INC)/linux
 LIBS = -lc
 
 all: clean libNativeThread.so
 
 NativeThread.class:
-	javac java/NativeThread.java
+	javac -classpath /opt/freenet/freenet-cvs-snapshot.jar java/NativeThread.java
+	mkdir -p freenet/support/io
 	mv java/NativeThread.class freenet/support/io/
 
 libNativeThread.so: NativeThread.c NativeThread.h
