#!/bin/sh
DIR=${HOME}/.dwm
mkdir -p "${DIR}"
if [ ! -p "${DIR}"/status ]; then
	rm -f "${DIR}"/status
	mkfifo "${DIR}"/status
fi
if [ -f "${DIR}"/dwmrc ]; then
	/bin/sh "${DIR}"/dwmrc >"${DIR}"/status &
else
	(while true; do
		echo `date`
		sleep 1
	done >"${DIR}"/status)&
fi
exec /usr/bin/dwm <"${DIR}"/status
