#!/sbin/runscript

opts="start stop reload"

depend() {
	need net
	after postgresql
}

start() {
	ebegin "Starting pgbouncer"
	
	start-stop-daemon --start --pidfile /var/run/pgbouncer/pgbouncer.pid \
		--exec /usr/bin/pgbouncer -- -d -u pgbouncer /etc/pgbouncer.conf
	eend $? "Failed to start pgbouncer"
}

stop() {
	ebegin "Stopping pgbouncer"
	start-stop-daemon --stop --quiet --pidfile /var/run/pgbouncer/pgbouncer.pid
	eend $?
} 

reload() {
	ebegin "Reloading pgbouncer configuration"
	kill -HUP `cat /var/run/pgbouncer/pgbouncer.pid`
	eend $?
}
