#!/sbin/runscript
# pgbouncer	Start the PgBouncer PostgreSQL pooler

opts="start stop reload checkconfig"

depend() {
	need net
	after postgresql
}

checkconfig(){
	test -f /etc/pgbouncer.conf
	result=$?
	eend $result
}

start() {
	checkconfig || return 1
	ebegin "Starting pgbouncer"
	
	start-stop-daemon --start --pidfile /var/run/pgbouncer/pgbouncer.pid \
		--exec /usr/bin/pgbouncer -- -d -u pgbouncer /etc/pgbouncer.conf
	eend $? "Failed to start pgbouncer"

}

stop() {
	ebegin "Stopping pgbouncer"
	start-stop-daemon --stop --quiet --pidfile /var/run/pgbouncer/pgbouncer.pid
	eend $?
} 

reload() {
	ebegin "Reloading pgbouncer configuration"
	kill -HUP `cat /var/run/pgbouncer/pgbouncer.pid`
	eend $?
}
